// RPC helpers validate unknown JSON at the service boundary. Motion additions in
// database.types.ts are generated by introspecting the migrated PostgreSQL fixture.
import type { SupabaseClient } from "@supabase/supabase-js";
import { getSupabaseServerClient } from "@/lib/supabase/server";
export function getMotionClient() {
  return getSupabaseServerClient() as unknown as SupabaseClient;
}
export type MotionRow = Record<string, unknown>;
