// Generated from the live Supabase PostgREST schema by scripts/generate-database-types.mjs.
// Do not edit manually.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      app_projects: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          name: string;
          brief: string;
          aspect: string;
          status: string;
          timeline_json: Json;
          transcript_edits_json: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          name: string;
          brief?: string;
          aspect?: string;
          status?: string;
          timeline_json: Json;
          transcript_edits_json: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          name?: string;
          brief?: string;
          aspect?: string;
          status?: string;
          timeline_json?: Json;
          transcript_edits_json?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      automation_drafts: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          automation_rule_id: string | null;
          youtube_channel_id: string;
          provider_video_id: string;
          source_asset_id: string | null;
          clip_job_id: string | null;
          title: string;
          description: string | null;
          thumbnail_url: string | null;
          duration_seconds: number | null;
          published_at: string | null;
          proposed_settings_json: Json;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          automation_rule_id?: string | null;
          youtube_channel_id: string;
          provider_video_id: string;
          source_asset_id?: string | null;
          clip_job_id?: string | null;
          title: string;
          description?: string | null;
          thumbnail_url?: string | null;
          duration_seconds?: number | null;
          published_at?: string | null;
          proposed_settings_json: Json;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          automation_rule_id?: string | null;
          youtube_channel_id?: string;
          provider_video_id?: string;
          source_asset_id?: string | null;
          clip_job_id?: string | null;
          title?: string;
          description?: string | null;
          thumbnail_url?: string | null;
          duration_seconds?: number | null;
          published_at?: string | null;
          proposed_settings_json?: Json;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      automation_events: {
        Row: {
          id: string;
          workspace_id: string;
          youtube_channel_id: string;
          automation_rule_id: string | null;
          provider_event_key: string;
          provider_video_id: string;
          event_kind: string;
          payload_json: Json;
          status: string;
          automation_draft_id: string | null;
          clip_job_id: string | null;
          received_at: string;
          processed_at: string | null;
          error_code: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          youtube_channel_id: string;
          automation_rule_id?: string | null;
          provider_event_key: string;
          provider_video_id: string;
          event_kind: string;
          payload_json: Json;
          status?: string;
          automation_draft_id?: string | null;
          clip_job_id?: string | null;
          received_at?: string;
          processed_at?: string | null;
          error_code?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          youtube_channel_id?: string;
          automation_rule_id?: string | null;
          provider_event_key?: string;
          provider_video_id?: string;
          event_kind?: string;
          payload_json?: Json;
          status?: string;
          automation_draft_id?: string | null;
          clip_job_id?: string | null;
          received_at?: string;
          processed_at?: string | null;
          error_code?: string | null;
        };
        Relationships: [];
      };
      automation_rules: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          youtube_channel_id: string;
          enabled: boolean;
          trigger_type: string;
          source_behavior: string;
          requested_clip_count: number;
          duration_range: string;
          caption_preset: string;
          content_type: string;
          clip_settings_json: Json;
          publishing_behavior: string;
          default_privacy: string;
          timezone: string;
          attestation_version: string | null;
          policy_version: string | null;
          rights_accepted_at: string | null;
          created_at: string;
          updated_at: string;
          connector_id: string;
          connector_connection_id: string | null;
          remote_collection_id: string | null;
          remote_collection_label: string | null;
          minimum_duration_seconds: number | null;
          maximum_duration_seconds: number | null;
          aspect_ratio: string;
          brand_preset_id: string | null;
          language: string;
          excluded_keywords: string[];
          publishing_destination_ids: string[];
          approval_mode: string;
          monthly_usage_ceiling_seconds: number | null;
          trigger_configuration_json: Json;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          youtube_channel_id: string;
          enabled?: boolean;
          trigger_type?: string;
          source_behavior?: string;
          requested_clip_count?: number;
          duration_range?: string;
          caption_preset?: string;
          content_type?: string;
          clip_settings_json: Json;
          publishing_behavior?: string;
          default_privacy?: string;
          timezone?: string;
          attestation_version?: string | null;
          policy_version?: string | null;
          rights_accepted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          connector_id?: string;
          connector_connection_id?: string | null;
          remote_collection_id?: string | null;
          remote_collection_label?: string | null;
          minimum_duration_seconds?: number | null;
          maximum_duration_seconds?: number | null;
          aspect_ratio?: string;
          brand_preset_id?: string | null;
          language?: string;
          excluded_keywords?: string[];
          publishing_destination_ids?: string[];
          approval_mode?: string;
          monthly_usage_ceiling_seconds?: number | null;
          trigger_configuration_json: Json;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          youtube_channel_id?: string;
          enabled?: boolean;
          trigger_type?: string;
          source_behavior?: string;
          requested_clip_count?: number;
          duration_range?: string;
          caption_preset?: string;
          content_type?: string;
          clip_settings_json?: Json;
          publishing_behavior?: string;
          default_privacy?: string;
          timezone?: string;
          attestation_version?: string | null;
          policy_version?: string | null;
          rights_accepted_at?: string | null;
          created_at?: string;
          updated_at?: string;
          connector_id?: string;
          connector_connection_id?: string | null;
          remote_collection_id?: string | null;
          remote_collection_label?: string | null;
          minimum_duration_seconds?: number | null;
          maximum_duration_seconds?: number | null;
          aspect_ratio?: string;
          brand_preset_id?: string | null;
          language?: string;
          excluded_keywords?: string[];
          publishing_destination_ids?: string[];
          approval_mode?: string;
          monthly_usage_ceiling_seconds?: number | null;
          trigger_configuration_json?: Json;
        };
        Relationships: [];
      };
      automation_source_runs: {
        Row: {
          id: string;
          workspace_id: string;
          automation_rule_id: string;
          connector_id: string;
          remote_asset_id: string;
          remote_version_id: string;
          connector_import_id: string | null;
          clip_job_id: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          automation_rule_id: string;
          connector_id: string;
          remote_asset_id: string;
          remote_version_id?: string;
          connector_import_id?: string | null;
          clip_job_id?: string | null;
          status: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          automation_rule_id?: string;
          connector_id?: string;
          remote_asset_id?: string;
          remote_version_id?: string;
          connector_import_id?: string | null;
          clip_job_id?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      billing_waitlist: {
        Row: {
          id: string;
          user_id: string;
          email: string;
          plan_interest: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          email: string;
          plan_interest?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          email?: string;
          plan_interest?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      clip_candidates: {
        Row: {
          id: string;
          clip_job_id: string;
          planning_run_id: string;
          start_seconds: number;
          end_seconds: number;
          title: string;
          hook: string;
          summary: string;
          topic: string;
          transcript_excerpt: string;
          standalone_score: number;
          hook_score: number;
          clarity_score: number;
          story_score: number;
          relevance_score: number;
          technical_score: number;
          overall_score: number;
          selection_reason: string;
          overlap_group: string | null;
          rank: number | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clip_job_id: string;
          planning_run_id: string;
          start_seconds: number;
          end_seconds: number;
          title: string;
          hook: string;
          summary: string;
          topic: string;
          transcript_excerpt: string;
          standalone_score: number;
          hook_score: number;
          clarity_score: number;
          story_score: number;
          relevance_score: number;
          technical_score: number;
          overall_score: number;
          selection_reason: string;
          overlap_group?: string | null;
          rank?: number | null;
          status: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clip_job_id?: string;
          planning_run_id?: string;
          start_seconds?: number;
          end_seconds?: number;
          title?: string;
          hook?: string;
          summary?: string;
          topic?: string;
          transcript_excerpt?: string;
          standalone_score?: number;
          hook_score?: number;
          clarity_score?: number;
          story_score?: number;
          relevance_score?: number;
          technical_score?: number;
          overall_score?: number;
          selection_reason?: string;
          overlap_group?: string | null;
          rank?: number | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      clip_jobs: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          project_id: string | null;
          source_asset_id: string | null;
          source_type: string;
          source_url: string | null;
          youtube_video_id: string | null;
          source_title: string | null;
          source_channel_id: string | null;
          source_channel_title: string | null;
          source_thumbnail_url: string | null;
          source_duration_seconds: number | null;
          source_language: string | null;
          content_type: string | null;
          target_platforms: string[];
          aspect_ratios: string[];
          settings_json: Json;
          requested_clip_count: number;
          completed_clip_count: number;
          status: string;
          priority: number;
          reserved_source_seconds: number;
          committed_source_seconds: number;
          watermark_required: boolean;
          export_limit_json: Json;
          retention_expires_at: string;
          error_code: string | null;
          error_message: string | null;
          created_at: string;
          updated_at: string;
          started_at: string | null;
          completed_at: string | null;
          cancelled_at: string | null;
          source_match_json: Json;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          project_id?: string | null;
          source_asset_id?: string | null;
          source_type: string;
          source_url?: string | null;
          youtube_video_id?: string | null;
          source_title?: string | null;
          source_channel_id?: string | null;
          source_channel_title?: string | null;
          source_thumbnail_url?: string | null;
          source_duration_seconds?: number | null;
          source_language?: string | null;
          content_type?: string | null;
          target_platforms?: string[];
          aspect_ratios?: string[];
          settings_json: Json;
          requested_clip_count?: number;
          completed_clip_count?: number;
          status?: string;
          priority?: number;
          reserved_source_seconds?: number;
          committed_source_seconds?: number;
          watermark_required: boolean;
          export_limit_json: Json;
          retention_expires_at?: string;
          error_code?: string | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          source_match_json: Json;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          project_id?: string | null;
          source_asset_id?: string | null;
          source_type?: string;
          source_url?: string | null;
          youtube_video_id?: string | null;
          source_title?: string | null;
          source_channel_id?: string | null;
          source_channel_title?: string | null;
          source_thumbnail_url?: string | null;
          source_duration_seconds?: number | null;
          source_language?: string | null;
          content_type?: string | null;
          target_platforms?: string[];
          aspect_ratios?: string[];
          settings_json?: Json;
          requested_clip_count?: number;
          completed_clip_count?: number;
          status?: string;
          priority?: number;
          reserved_source_seconds?: number;
          committed_source_seconds?: number;
          watermark_required?: boolean;
          export_limit_json?: Json;
          retention_expires_at?: string;
          error_code?: string | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          source_match_json?: Json;
        };
        Relationships: [];
      };
      clip_versions: {
        Row: {
          id: string;
          clip_id: string;
          version_number: number;
          created_by: string;
          created_source: string;
          edit_manifest_json: Json;
          transcript_edits_json: Json;
          caption_settings_json: Json;
          crop_settings_json: Json;
          audio_settings_json: Json;
          text_overlays_json: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          clip_id: string;
          version_number: number;
          created_by: string;
          created_source: string;
          edit_manifest_json: Json;
          transcript_edits_json: Json;
          caption_settings_json: Json;
          crop_settings_json: Json;
          audio_settings_json: Json;
          text_overlays_json: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          clip_id?: string;
          version_number?: number;
          created_by?: string;
          created_source?: string;
          edit_manifest_json?: Json;
          transcript_edits_json?: Json;
          caption_settings_json?: Json;
          crop_settings_json?: Json;
          audio_settings_json?: Json;
          text_overlays_json?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      clips: {
        Row: {
          id: string;
          clip_job_id: string;
          clip_candidate_id: string | null;
          current_version_id: string | null;
          title: string;
          status: string;
          selected: boolean;
          duration_seconds: number;
          preview_asset_id: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          clip_job_id: string;
          clip_candidate_id?: string | null;
          current_version_id?: string | null;
          title: string;
          status: string;
          selected?: boolean;
          duration_seconds: number;
          preview_asset_id?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          clip_job_id?: string;
          clip_candidate_id?: string | null;
          current_version_id?: string | null;
          title?: string;
          status?: string;
          selected?: boolean;
          duration_seconds?: number;
          preview_asset_id?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      connector_audit_events: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          connector_id: string;
          event_type: string;
          metadata_json: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          connector_id: string;
          event_type: string;
          metadata_json: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          connector_id?: string;
          event_type?: string;
          metadata_json?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      connector_connections: {
        Row: {
          id: string | null;
          workspace_id: string | null;
          user_id: string | null;
          connector_id: string | null;
          provider_account_id: string | null;
          display_name: string | null;
          token_expires_at: string | null;
          scopes: string[] | null;
          status: string | null;
          error_code: string | null;
          connected_at: string | null;
          last_used_at: string | null;
          last_health_check_at: string | null;
          revoked_at: string | null;
          metadata_json: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string | null;
          workspace_id?: string | null;
          user_id?: string | null;
          connector_id?: string | null;
          provider_account_id?: string | null;
          display_name?: string | null;
          token_expires_at?: string | null;
          scopes?: string[] | null;
          status?: string | null;
          error_code?: string | null;
          connected_at?: string | null;
          last_used_at?: string | null;
          last_health_check_at?: string | null;
          revoked_at?: string | null;
          metadata_json?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string | null;
          workspace_id?: string | null;
          user_id?: string | null;
          connector_id?: string | null;
          provider_account_id?: string | null;
          display_name?: string | null;
          token_expires_at?: string | null;
          scopes?: string[] | null;
          status?: string | null;
          error_code?: string | null;
          connected_at?: string | null;
          last_used_at?: string | null;
          last_health_check_at?: string | null;
          revoked_at?: string | null;
          metadata_json?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      connector_definitions: {
        Row: {
          id: string;
          label: string;
          category: string;
          availability: string;
          capabilities: string[];
          feature_flag: string | null;
          configuration_json: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          label: string;
          category: string;
          availability: string;
          capabilities?: string[];
          feature_flag?: string | null;
          configuration_json: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          label?: string;
          category?: string;
          availability?: string;
          capabilities?: string[];
          feature_flag?: string | null;
          configuration_json?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      connector_imports: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          connector_connection_id: string | null;
          connector_id: string;
          remote_asset_id: string | null;
          remote_asset_url: string | null;
          source_metadata_json: Json;
          destination_asset_id: string | null;
          status: string;
          bytes_total: number | null;
          bytes_transferred: number;
          checksum: string | null;
          attempt: number;
          idempotency_key: string;
          error_code: string | null;
          error_message: string | null;
          created_at: string;
          started_at: string | null;
          completed_at: string | null;
          cancelled_at: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          connector_connection_id?: string | null;
          connector_id: string;
          remote_asset_id?: string | null;
          remote_asset_url?: string | null;
          source_metadata_json: Json;
          destination_asset_id?: string | null;
          status?: string;
          bytes_total?: number | null;
          bytes_transferred?: number;
          checksum?: string | null;
          attempt?: number;
          idempotency_key: string;
          error_code?: string | null;
          error_message?: string | null;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          connector_connection_id?: string | null;
          connector_id?: string;
          remote_asset_id?: string | null;
          remote_asset_url?: string | null;
          source_metadata_json?: Json;
          destination_asset_id?: string | null;
          status?: string;
          bytes_total?: number | null;
          bytes_transferred?: number;
          checksum?: string | null;
          attempt?: number;
          idempotency_key?: string;
          error_code?: string | null;
          error_message?: string | null;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      connector_tasks: {
        Row: {
          id: string;
          connector_import_id: string;
          task_type: string;
          status: string;
          input_json: Json;
          output_json: Json;
          attempt: number;
          max_attempts: number;
          priority: number;
          idempotency_key: string;
          lease_owner: string | null;
          lease_expires_at: string | null;
          last_heartbeat_at: string | null;
          progress_current: number | null;
          progress_total: number | null;
          next_attempt_at: string;
          error_code: string | null;
          error_message: string | null;
          created_at: string;
          started_at: string | null;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          connector_import_id: string;
          task_type: string;
          status?: string;
          input_json: Json;
          output_json: Json;
          attempt?: number;
          max_attempts?: number;
          priority?: number;
          idempotency_key: string;
          lease_owner?: string | null;
          lease_expires_at?: string | null;
          last_heartbeat_at?: string | null;
          progress_current?: number | null;
          progress_total?: number | null;
          next_attempt_at?: string;
          error_code?: string | null;
          error_message?: string | null;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          connector_import_id?: string;
          task_type?: string;
          status?: string;
          input_json?: Json;
          output_json?: Json;
          attempt?: number;
          max_attempts?: number;
          priority?: number;
          idempotency_key?: string;
          lease_owner?: string | null;
          lease_expires_at?: string | null;
          last_heartbeat_at?: string | null;
          progress_current?: number | null;
          progress_total?: number | null;
          next_attempt_at?: string;
          error_code?: string | null;
          error_message?: string | null;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      connector_waitlist: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          connector_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          connector_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          connector_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      exports: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          clip_job_id: string;
          clip_id: string | null;
          render_job_id: string | null;
          export_type: string;
          format: string;
          resolution: string;
          frame_rate: number;
          caption_mode: string;
          watermarked: boolean;
          storage_bucket: string | null;
          storage_path: string | null;
          size_bytes: number | null;
          checksum_sha256: string | null;
          status: string;
          expires_at: string;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          clip_job_id: string;
          clip_id?: string | null;
          render_job_id?: string | null;
          export_type: string;
          format: string;
          resolution: string;
          frame_rate: number;
          caption_mode: string;
          watermarked: boolean;
          storage_bucket?: string | null;
          storage_path?: string | null;
          size_bytes?: number | null;
          checksum_sha256?: string | null;
          status: string;
          expires_at?: string;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          clip_job_id?: string;
          clip_id?: string | null;
          render_job_id?: string | null;
          export_type?: string;
          format?: string;
          resolution?: string;
          frame_rate?: number;
          caption_mode?: string;
          watermarked?: boolean;
          storage_bucket?: string | null;
          storage_path?: string | null;
          size_bytes?: number | null;
          checksum_sha256?: string | null;
          status?: string;
          expires_at?: string;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      job_tasks: {
        Row: {
          id: string;
          clip_job_id: string;
          task_type: string;
          status: string;
          priority: number;
          dependency_group: string | null;
          input_json: Json;
          output_json: Json;
          attempt: number;
          max_attempts: number;
          idempotency_key: string;
          lease_owner: string | null;
          lease_expires_at: string | null;
          heartbeat_at: string | null;
          next_attempt_at: string | null;
          progress_current: number | null;
          progress_total: number | null;
          error_code: string | null;
          error_message: string | null;
          created_at: string;
          started_at: string | null;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          clip_job_id: string;
          task_type: string;
          status?: string;
          priority?: number;
          dependency_group?: string | null;
          input_json: Json;
          output_json: Json;
          attempt?: number;
          max_attempts?: number;
          idempotency_key: string;
          lease_owner?: string | null;
          lease_expires_at?: string | null;
          heartbeat_at?: string | null;
          next_attempt_at?: string | null;
          progress_current?: number | null;
          progress_total?: number | null;
          error_code?: string | null;
          error_message?: string | null;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          clip_job_id?: string;
          task_type?: string;
          status?: string;
          priority?: number;
          dependency_group?: string | null;
          input_json?: Json;
          output_json?: Json;
          attempt?: number;
          max_attempts?: number;
          idempotency_key?: string;
          lease_owner?: string | null;
          lease_expires_at?: string | null;
          heartbeat_at?: string | null;
          next_attempt_at?: string | null;
          progress_current?: number | null;
          progress_total?: number | null;
          error_code?: string | null;
          error_message?: string | null;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      media_assets: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          project_id: string | null;
          source_type: string;
          storage_bucket: string | null;
          storage_path: string | null;
          original_filename: string | null;
          display_name: string;
          mime_type: string | null;
          size_bytes: number | null;
          checksum_sha256: string | null;
          duration_seconds: number | null;
          width: number | null;
          height: number | null;
          frame_rate: number | null;
          video_codec: string | null;
          audio_codec: string | null;
          has_audio: boolean | null;
          status: string;
          metadata_json: Json;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          project_id?: string | null;
          source_type: string;
          storage_bucket?: string | null;
          storage_path?: string | null;
          original_filename?: string | null;
          display_name: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          checksum_sha256?: string | null;
          duration_seconds?: number | null;
          width?: number | null;
          height?: number | null;
          frame_rate?: number | null;
          video_codec?: string | null;
          audio_codec?: string | null;
          has_audio?: boolean | null;
          status?: string;
          metadata_json: Json;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          project_id?: string | null;
          source_type?: string;
          storage_bucket?: string | null;
          storage_path?: string | null;
          original_filename?: string | null;
          display_name?: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          checksum_sha256?: string | null;
          duration_seconds?: number | null;
          width?: number | null;
          height?: number | null;
          frame_rate?: number | null;
          video_codec?: string | null;
          audio_codec?: string | null;
          has_audio?: boolean | null;
          status?: string;
          metadata_json?: Json;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      oauth_connections: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          provider: string;
          access_token_encrypted: string | null;
          refresh_token_encrypted: string | null;
          token_expires_at: string | null;
          scopes: string[];
          provider_account_id: string | null;
          metadata_json: Json;
          created_at: string;
          updated_at: string;
          status: string;
          capabilities: string[];
          token_version: number;
          last_refreshed_at: string | null;
          last_verified_at: string | null;
          last_error_code: string | null;
          disconnected_at: string | null;
          connector_id: string;
          display_name: string | null;
          connected_at: string | null;
          last_used_at: string | null;
          last_health_check_at: string | null;
          revoked_at: string | null;
          error_code: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          provider: string;
          access_token_encrypted?: string | null;
          refresh_token_encrypted?: string | null;
          token_expires_at?: string | null;
          scopes?: string[];
          provider_account_id?: string | null;
          metadata_json: Json;
          created_at?: string;
          updated_at?: string;
          status?: string;
          capabilities?: string[];
          token_version?: number;
          last_refreshed_at?: string | null;
          last_verified_at?: string | null;
          last_error_code?: string | null;
          disconnected_at?: string | null;
          connector_id: string;
          display_name?: string | null;
          connected_at?: string | null;
          last_used_at?: string | null;
          last_health_check_at?: string | null;
          revoked_at?: string | null;
          error_code?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          provider?: string;
          access_token_encrypted?: string | null;
          refresh_token_encrypted?: string | null;
          token_expires_at?: string | null;
          scopes?: string[];
          provider_account_id?: string | null;
          metadata_json?: Json;
          created_at?: string;
          updated_at?: string;
          status?: string;
          capabilities?: string[];
          token_version?: number;
          last_refreshed_at?: string | null;
          last_verified_at?: string | null;
          last_error_code?: string | null;
          disconnected_at?: string | null;
          connector_id?: string;
          display_name?: string | null;
          connected_at?: string | null;
          last_used_at?: string | null;
          last_health_check_at?: string | null;
          revoked_at?: string | null;
          error_code?: string | null;
        };
        Relationships: [];
      };
      oauth_states: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          connector_id: string;
          state_hash: string;
          code_verifier_encrypted: string;
          return_url: string;
          expires_at: string;
          consumed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          connector_id: string;
          state_hash: string;
          code_verifier_encrypted: string;
          return_url: string;
          expires_at?: string;
          consumed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          connector_id?: string;
          state_hash?: string;
          code_verifier_encrypted?: string;
          return_url?: string;
          expires_at?: string;
          consumed_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      outbox_events: {
        Row: {
          id: string;
          aggregate_type: string;
          aggregate_id: string;
          event_type: string;
          payload_json: Json;
          status: string;
          attempt: number;
          next_attempt_at: string;
          created_at: string;
          processed_at: string | null;
        };
        Insert: {
          id?: string;
          aggregate_type: string;
          aggregate_id: string;
          event_type: string;
          payload_json: Json;
          status?: string;
          attempt?: number;
          next_attempt_at?: string;
          created_at?: string;
          processed_at?: string | null;
        };
        Update: {
          id?: string;
          aggregate_type?: string;
          aggregate_id?: string;
          event_type?: string;
          payload_json?: Json;
          status?: string;
          attempt?: number;
          next_attempt_at?: string;
          created_at?: string;
          processed_at?: string | null;
        };
        Relationships: [];
      };
      planning_runs: {
        Row: {
          id: string;
          clip_job_id: string;
          provider: string;
          model: string;
          prompt_version: string;
          schema_version: string;
          status: string;
          input_token_count: number | null;
          output_token_count: number | null;
          estimated_cost: number | null;
          latency_ms: number | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          clip_job_id: string;
          provider: string;
          model: string;
          prompt_version: string;
          schema_version: string;
          status: string;
          input_token_count?: number | null;
          output_token_count?: number | null;
          estimated_cost?: number | null;
          latency_ms?: number | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          clip_job_id?: string;
          provider?: string;
          model?: string;
          prompt_version?: string;
          schema_version?: string;
          status?: string;
          input_token_count?: number | null;
          output_token_count?: number | null;
          estimated_cost?: number | null;
          latency_ms?: number | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      plans: {
        Row: {
          key: string;
          name: string;
          monthly_source_seconds: number;
          max_source_seconds_per_job: number;
          max_clips_per_job: number;
          max_concurrent_jobs: number;
          max_export_height: number;
          max_export_width: number;
          max_export_fps: number;
          watermark_required: boolean;
          trial_unwatermarked_exports: number;
          retention_days: number;
          max_reprompts_per_job: number;
          brand_preset_limit: number;
          priority: number;
          active: boolean;
          max_connector_connections: number;
          max_automation_rules: number;
          s3_connector_enabled: boolean;
          publishing_connections_enabled: boolean;
          api_beta_enabled: boolean;
        };
        Insert: {
          key: string;
          name: string;
          monthly_source_seconds: number;
          max_source_seconds_per_job: number;
          max_clips_per_job: number;
          max_concurrent_jobs: number;
          max_export_height: number;
          max_export_width: number;
          max_export_fps: number;
          watermark_required: boolean;
          trial_unwatermarked_exports?: number;
          retention_days: number;
          max_reprompts_per_job: number;
          brand_preset_limit: number;
          priority: number;
          active?: boolean;
          max_connector_connections?: number;
          max_automation_rules?: number;
          s3_connector_enabled?: boolean;
          publishing_connections_enabled?: boolean;
          api_beta_enabled?: boolean;
        };
        Update: {
          key?: string;
          name?: string;
          monthly_source_seconds?: number;
          max_source_seconds_per_job?: number;
          max_clips_per_job?: number;
          max_concurrent_jobs?: number;
          max_export_height?: number;
          max_export_width?: number;
          max_export_fps?: number;
          watermark_required?: boolean;
          trial_unwatermarked_exports?: number;
          retention_days?: number;
          max_reprompts_per_job?: number;
          brand_preset_limit?: number;
          priority?: number;
          active?: boolean;
          max_connector_connections?: number;
          max_automation_rules?: number;
          s3_connector_enabled?: boolean;
          publishing_connections_enabled?: boolean;
          api_beta_enabled?: boolean;
        };
        Relationships: [];
      };
      processing_events: {
        Row: {
          id: string;
          clip_job_id: string;
          job_task_id: string | null;
          stage: string;
          severity: string;
          message: string;
          progress_current: number | null;
          progress_total: number | null;
          correlation_id: string;
          provider: string | null;
          attempt: number | null;
          created_at: string;
          proxy_tier: string | null;
        };
        Insert: {
          id?: string;
          clip_job_id: string;
          job_task_id?: string | null;
          stage: string;
          severity: string;
          message: string;
          progress_current?: number | null;
          progress_total?: number | null;
          correlation_id?: string;
          provider?: string | null;
          attempt?: number | null;
          created_at?: string;
          proxy_tier?: string | null;
        };
        Update: {
          id?: string;
          clip_job_id?: string;
          job_task_id?: string | null;
          stage?: string;
          severity?: string;
          message?: string;
          progress_current?: number | null;
          progress_total?: number | null;
          correlation_id?: string;
          provider?: string | null;
          attempt?: number | null;
          created_at?: string;
          proxy_tier?: string | null;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          display_name: string | null;
          avatar_url: string | null;
          plan_key: string;
          trial_unwatermarked_exports_used: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          display_name?: string | null;
          avatar_url?: string | null;
          plan_key?: string;
          trial_unwatermarked_exports_used?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          plan_key?: string;
          trial_unwatermarked_exports_used?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      project_templates: {
        Row: {
          id: string;
          workspace_id: string | null;
          user_id: string | null;
          slug: string;
          name: string;
          description: string;
          aspect: string;
          brief: string;
          icon: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id?: string | null;
          user_id?: string | null;
          slug: string;
          name: string;
          description: string;
          aspect: string;
          brief: string;
          icon?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string | null;
          user_id?: string | null;
          slug?: string;
          name?: string;
          description?: string;
          aspect?: string;
          brief?: string;
          icon?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      project_versions: {
        Row: {
          id: string;
          project_id: string;
          workspace_id: string;
          user_id: string;
          label: string;
          kind: string;
          summary: string;
          timeline_json: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          workspace_id: string;
          user_id: string;
          label: string;
          kind?: string;
          summary?: string;
          timeline_json: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          workspace_id?: string;
          user_id?: string;
          label?: string;
          kind?: string;
          summary?: string;
          timeline_json?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      provider_runs: {
        Row: {
          id: string;
          clip_job_id: string;
          job_task_id: string | null;
          provider: string;
          model: string;
          feature: string;
          request_id: string | null;
          status: string;
          input_units: number | null;
          output_units: number | null;
          estimated_cost: number | null;
          latency_ms: number | null;
          retry_count: number;
          error_category: string | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          clip_job_id: string;
          job_task_id?: string | null;
          provider: string;
          model: string;
          feature: string;
          request_id?: string | null;
          status: string;
          input_units?: number | null;
          output_units?: number | null;
          estimated_cost?: number | null;
          latency_ms?: number | null;
          retry_count?: number;
          error_category?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          clip_job_id?: string;
          job_task_id?: string | null;
          provider?: string;
          model?: string;
          feature?: string;
          request_id?: string | null;
          status?: string;
          input_units?: number | null;
          output_units?: number | null;
          estimated_cost?: number | null;
          latency_ms?: number | null;
          retry_count?: number;
          error_category?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      publishing_jobs: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          clip_job_id: string;
          export_id: string;
          youtube_channel_id: string;
          title: string;
          description: string;
          tags: string[];
          category_id: string;
          made_for_kids: boolean;
          privacy_status: string;
          scheduled_for: string | null;
          status: string;
          idempotency_key: string;
          provider_video_id: string | null;
          provider_video_url: string | null;
          resumable_session_encrypted: string | null;
          attempt: number;
          last_error_code: string | null;
          last_error_message: string | null;
          created_at: string;
          updated_at: string;
          started_at: string | null;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          clip_job_id: string;
          export_id: string;
          youtube_channel_id: string;
          title: string;
          description?: string;
          tags?: string[];
          category_id?: string;
          made_for_kids: boolean;
          privacy_status?: string;
          scheduled_for?: string | null;
          status?: string;
          idempotency_key: string;
          provider_video_id?: string | null;
          provider_video_url?: string | null;
          resumable_session_encrypted?: string | null;
          attempt?: number;
          last_error_code?: string | null;
          last_error_message?: string | null;
          created_at?: string;
          updated_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          clip_job_id?: string;
          export_id?: string;
          youtube_channel_id?: string;
          title?: string;
          description?: string;
          tags?: string[];
          category_id?: string;
          made_for_kids?: boolean;
          privacy_status?: string;
          scheduled_for?: string | null;
          status?: string;
          idempotency_key?: string;
          provider_video_id?: string | null;
          provider_video_url?: string | null;
          resumable_session_encrypted?: string | null;
          attempt?: number;
          last_error_code?: string | null;
          last_error_message?: string | null;
          created_at?: string;
          updated_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      render_jobs: {
        Row: {
          id: string;
          clip_job_id: string;
          clip_id: string | null;
          clip_version_id: string | null;
          render_type: string;
          status: string;
          settings_json: Json;
          watermark_required: boolean;
          output_asset_id: string | null;
          attempt: number;
          idempotency_key: string;
          error_code: string | null;
          error_message: string | null;
          created_at: string;
          started_at: string | null;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          clip_job_id: string;
          clip_id?: string | null;
          clip_version_id?: string | null;
          render_type: string;
          status: string;
          settings_json: Json;
          watermark_required: boolean;
          output_asset_id?: string | null;
          attempt?: number;
          idempotency_key: string;
          error_code?: string | null;
          error_message?: string | null;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          clip_job_id?: string;
          clip_id?: string | null;
          clip_version_id?: string | null;
          render_type?: string;
          status?: string;
          settings_json?: Json;
          watermark_required?: boolean;
          output_asset_id?: string | null;
          attempt?: number;
          idempotency_key?: string;
          error_code?: string | null;
          error_message?: string | null;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      rights_attestations: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          clip_job_id: string;
          source_url: string | null;
          source_identifier: string | null;
          attestation_version: string;
          policy_version: string;
          accepted_at: string;
          request_metadata_json: Json;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          clip_job_id: string;
          source_url?: string | null;
          source_identifier?: string | null;
          attestation_version: string;
          policy_version: string;
          accepted_at?: string;
          request_metadata_json: Json;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          clip_job_id?: string;
          source_url?: string | null;
          source_identifier?: string | null;
          attestation_version?: string;
          policy_version?: string;
          accepted_at?: string;
          request_metadata_json?: Json;
        };
        Relationships: [];
      };
      source_attachments: {
        Row: {
          id: string;
          clip_job_id: string;
          connector_id: string;
          connector_import_id: string | null;
          media_asset_id: string | null;
          youtube_video_id: string | null;
          relationship: string;
          match_confidence: number | null;
          match_reason: string | null;
          created_at: string;
          idempotency_key: string | null;
        };
        Insert: {
          id?: string;
          clip_job_id: string;
          connector_id: string;
          connector_import_id?: string | null;
          media_asset_id?: string | null;
          youtube_video_id?: string | null;
          relationship: string;
          match_confidence?: number | null;
          match_reason?: string | null;
          created_at?: string;
          idempotency_key?: string | null;
        };
        Update: {
          id?: string;
          clip_job_id?: string;
          connector_id?: string;
          connector_import_id?: string | null;
          media_asset_id?: string | null;
          youtube_video_id?: string | null;
          relationship?: string;
          match_confidence?: number | null;
          match_reason?: string | null;
          created_at?: string;
          idempotency_key?: string | null;
        };
        Relationships: [];
      };
      support_requests: {
        Row: {
          id: string;
          user_id: string | null;
          name: string;
          email: string;
          topic: string;
          message: string;
          status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          name: string;
          email: string;
          topic: string;
          message: string;
          status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          name?: string;
          email?: string;
          topic?: string;
          message?: string;
          status?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      transcript_segments: {
        Row: {
          id: string;
          transcript_id: string;
          sequence: number;
          speaker_key: string | null;
          start_seconds: number;
          end_seconds: number;
          text: string;
          confidence: number | null;
          words_json: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          transcript_id: string;
          sequence: number;
          speaker_key?: string | null;
          start_seconds: number;
          end_seconds: number;
          text: string;
          confidence?: number | null;
          words_json: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          transcript_id?: string;
          sequence?: number;
          speaker_key?: string | null;
          start_seconds?: number;
          end_seconds?: number;
          text?: string;
          confidence?: number | null;
          words_json?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      transcripts: {
        Row: {
          id: string;
          clip_job_id: string;
          media_asset_id: string;
          language: string | null;
          provider: string;
          model: string;
          duration_seconds: number | null;
          text: string;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clip_job_id: string;
          media_asset_id: string;
          language?: string | null;
          provider: string;
          model: string;
          duration_seconds?: number | null;
          text?: string;
          status: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clip_job_id?: string;
          media_asset_id?: string;
          language?: string | null;
          provider?: string;
          model?: string;
          duration_seconds?: number | null;
          text?: string;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      usage_ledger: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          job_id: string | null;
          category: string;
          amount: number;
          unit: string;
          direction: string;
          state: string;
          idempotency_key: string;
          description: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          job_id?: string | null;
          category: string;
          amount: number;
          unit: string;
          direction: string;
          state: string;
          idempotency_key: string;
          description: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          job_id?: string | null;
          category?: string;
          amount?: number;
          unit?: string;
          direction?: string;
          state?: string;
          idempotency_key?: string;
          description?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      usage_periods: {
        Row: {
          id: string;
          workspace_id: string;
          plan_key: string;
          period_start: string;
          period_end: string;
          source_seconds_limit: number;
          source_seconds_reserved: number;
          source_seconds_committed: number;
          generation_credits_limit: number;
          generation_credits_reserved: number;
          generation_credits_committed: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          plan_key: string;
          period_start: string;
          period_end: string;
          source_seconds_limit: number;
          source_seconds_reserved?: number;
          source_seconds_committed?: number;
          generation_credits_limit?: number;
          generation_credits_reserved?: number;
          generation_credits_committed?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          plan_key?: string;
          period_start?: string;
          period_end?: string;
          source_seconds_limit?: number;
          source_seconds_reserved?: number;
          source_seconds_committed?: number;
          generation_credits_limit?: number;
          generation_credits_reserved?: number;
          generation_credits_committed?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      user_preferences: {
        Row: {
          user_id: string;
          workspace_id: string;
          ai_plan_preview: boolean;
          autosave_seconds: number;
          snap_to_words: boolean;
          low_resolution_preview: boolean;
          notify_export_complete: boolean;
          notify_ai_plan_complete: boolean;
          notify_weekly_usage: boolean;
          notify_product_updates: boolean;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          workspace_id: string;
          ai_plan_preview?: boolean;
          autosave_seconds?: number;
          snap_to_words?: boolean;
          low_resolution_preview?: boolean;
          notify_export_complete?: boolean;
          notify_ai_plan_complete?: boolean;
          notify_weekly_usage?: boolean;
          notify_product_updates?: boolean;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          workspace_id?: string;
          ai_plan_preview?: boolean;
          autosave_seconds?: number;
          snap_to_words?: boolean;
          low_resolution_preview?: boolean;
          notify_export_complete?: boolean;
          notify_ai_plan_complete?: boolean;
          notify_weekly_usage?: boolean;
          notify_product_updates?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      workspace_members: {
        Row: {
          workspace_id: string;
          user_id: string;
          role: string;
          created_at: string;
        };
        Insert: {
          workspace_id: string;
          user_id: string;
          role: string;
          created_at?: string;
        };
        Update: {
          workspace_id?: string;
          user_id?: string;
          role?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      workspaces: {
        Row: {
          id: string;
          name: string;
          owner_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          owner_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          owner_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      youtube_asset_links: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          youtube_channel_id: string;
          provider_video_id: string;
          media_asset_id: string;
          provenance: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          youtube_channel_id: string;
          provider_video_id: string;
          media_asset_id: string;
          provenance: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          youtube_channel_id?: string;
          provider_video_id?: string;
          media_asset_id?: string;
          provenance?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      youtube_channels: {
        Row: {
          id: string;
          connection_id: string;
          workspace_id: string;
          user_id: string;
          provider_channel_id: string;
          title: string;
          avatar_url: string | null;
          uploads_playlist_id: string | null;
          selected: boolean;
          last_observed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          connection_id: string;
          workspace_id: string;
          user_id: string;
          provider_channel_id: string;
          title: string;
          avatar_url?: string | null;
          uploads_playlist_id?: string | null;
          selected?: boolean;
          last_observed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          connection_id?: string;
          workspace_id?: string;
          user_id?: string;
          provider_channel_id?: string;
          title?: string;
          avatar_url?: string | null;
          uploads_playlist_id?: string | null;
          selected?: boolean;
          last_observed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      youtube_subscriptions: {
        Row: {
          id: string;
          workspace_id: string;
          youtube_channel_id: string;
          hub_topic: string;
          callback_key: string;
          secret_hash: string;
          status: string;
          lease_expires_at: string | null;
          last_renewal_attempt_at: string | null;
          verified_at: string | null;
          last_error_code: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          youtube_channel_id: string;
          hub_topic: string;
          callback_key?: string;
          secret_hash: string;
          status?: string;
          lease_expires_at?: string | null;
          last_renewal_attempt_at?: string | null;
          verified_at?: string | null;
          last_error_code?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          youtube_channel_id?: string;
          hub_topic?: string;
          callback_key?: string;
          secret_hash?: string;
          status?: string;
          lease_expires_at?: string | null;
          last_renewal_attempt_at?: string | null;
          verified_at?: string | null;
          last_error_code?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      create_automated_clip_job: {
        Args: {
          p_rule_id: string;
          p_draft_id: string;
          p_source_asset_id: string;
          p_idempotency_key: string;
        };
        Returns: string;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
