import type { ConnectorDefinition } from "./types";

type Seed = Omit<
  ConnectorDefinition,
  "requiresRightsConfirmation" | "requiresOriginalSource" | "supportsPublicLinks"
> &
  Partial<
    Pick<
      ConnectorDefinition,
      "requiresRightsConfirmation" | "requiresOriginalSource" | "supportsPublicLinks"
    >
  >;

const define = (seed: Seed): ConnectorDefinition => ({
  requiresRightsConfirmation: true,
  requiresOriginalSource: false,
  supportsPublicLinks: false,
  ...seed,
});

const comingSoon = (
  id: string,
  label: string,
  category: ConnectorDefinition["category"],
  description: string,
  icon: ConnectorDefinition["icon"] = "other",
  authentication: ConnectorDefinition["authentication"] = "oauth",
): ConnectorDefinition =>
  define({
    id,
    label,
    category,
    description,
    icon,
    authentication,
    availability: "coming_soon",
    capabilities: [],
  });

export const CONNECTOR_REGISTRY = [
  define({
    id: "local_upload",
    label: "Upload from device",
    description:
      "Upload an original MP4, MOV, MKV, WebM, or M4V file privately with resumable transfer.",
    category: "uploads",
    availability: "available",
    capabilities: ["metadata", "resumable_import"],
    authentication: "none",
    icon: "upload",
    searchTerms: ["file", "device", "video"],
  }),
  define({
    id: "youtube",
    label: "YouTube",
    description:
      "Retrieve official metadata, connect a channel, and attach the original media for rendering.",
    category: "video_platforms",
    availability: "available",
    capabilities: ["metadata", "playlist", "channel_automation", "webhook", "publish", "schedule"],
    authentication: "oauth",
    icon: "youtube",
    requiresOriginalSource: true,
    supportsPublicLinks: true,
    searchTerms: ["shorts", "channel", "playlist"],
  }),
  define({
    id: "direct_url",
    label: "Paste media link",
    description:
      "Import an owner-controlled HTTPS media file through Vidrial's protected downloader.",
    category: "direct_links",
    availability: "available",
    capabilities: ["metadata", "download_original"],
    authentication: "none",
    icon: "link",
    supportsPublicLinks: true,
    searchTerms: ["url", "https", "media file"],
  }),
  define({
    id: "rss",
    label: "Podcast RSS",
    description: "Resolve a public RSS or Atom feed and import an authorised episode enclosure.",
    category: "podcast_audio",
    availability: "available",
    capabilities: ["metadata", "search", "download_original", "captions"],
    authentication: "none",
    icon: "podcast",
    supportsPublicLinks: true,
    searchTerms: ["atom", "apple podcasts", "episode", "feed"],
  }),
  define({
    id: "google_drive",
    label: "Google Drive",
    description:
      "Browse and import authorised video or audio files from My Drive or Shared with me.",
    category: "cloud_storage",
    availability: "beta",
    capabilities: ["metadata", "browse", "search", "download_original", "resumable_import"],
    authentication: "oauth",
    icon: "cloud",
    featureFlag: "GOOGLE_DRIVE_CONNECTOR",
    searchTerms: ["shared with me", "google workspace"],
  }),
  define({
    id: "dropbox",
    label: "Dropbox",
    description: "Choose video or audio files and import them using an authorised temporary link.",
    category: "cloud_storage",
    availability: "beta",
    capabilities: ["metadata", "browse", "search", "download_original", "resumable_import"],
    authentication: "oauth",
    icon: "cloud",
    featureFlag: "DROPBOX_CONNECTOR",
  }),
  define({
    id: "onedrive",
    label: "OneDrive",
    description: "Browse personal or business Microsoft storage and import authorised media.",
    category: "cloud_storage",
    availability: "beta",
    capabilities: ["metadata", "browse", "search", "download_original", "resumable_import"],
    authentication: "oauth",
    icon: "cloud",
    featureFlag: "ONEDRIVE_CONNECTOR",
    searchTerms: ["microsoft", "sharepoint"],
  }),
  define({
    id: "s3",
    label: "S3-compatible storage",
    description: "Import a signed object from AWS S3, R2, B2, MinIO, or another compatible store.",
    category: "cloud_storage",
    availability: "beta",
    capabilities: ["metadata", "download_original", "resumable_import", "webhook"],
    authentication: "signed_url",
    icon: "database",
    featureFlag: "S3_CONNECTOR",
    supportsPublicLinks: true,
    searchTerms: ["aws", "r2", "backblaze", "b2", "minio", "presigned"],
  }),
  define({
    id: "vimeo",
    label: "Vimeo",
    description: "Use official metadata and authorised downloadable files from your Vimeo library.",
    category: "video_platforms",
    availability: "beta",
    capabilities: ["metadata", "browse", "search", "download_original"],
    authentication: "oauth",
    icon: "video",
    featureFlag: "VIMEO_CONNECTOR",
    supportsPublicLinks: true,
  }),
  define({
    id: "zoom",
    label: "Zoom",
    description: "Choose a cloud recording and its available transcript from a connected account.",
    category: "recording_platforms",
    availability: "beta",
    capabilities: ["metadata", "browse", "search", "download_original", "captions"],
    authentication: "oauth",
    icon: "recording",
    featureFlag: "ZOOM_CONNECTOR",
    supportsPublicLinks: true,
  }),
  define({
    id: "loom",
    label: "Loom",
    description:
      "Import user-owned recordings when the official integration exposes a downloadable asset.",
    category: "recording_platforms",
    availability: "beta",
    capabilities: ["metadata", "browse", "download_original"],
    authentication: "oauth",
    icon: "recording",
    featureFlag: "LOOM_CONNECTOR",
    supportsPublicLinks: true,
  }),
  define({
    id: "riverside",
    label: "Riverside",
    description: "Import supported recording exports, tracks, transcripts, and captions.",
    category: "recording_platforms",
    availability: "beta",
    capabilities: ["metadata", "browse", "download_original", "captions"],
    authentication: "api_key",
    icon: "recording",
    featureFlag: "RIVERSIDE_CONNECTOR",
    supportsPublicLinks: true,
  }),
  define({
    id: "frameio",
    label: "Frame.io",
    description: "Browse projects and versions, then select an authorised original or proxy asset.",
    category: "cloud_storage",
    availability: "beta",
    capabilities: ["metadata", "browse", "search", "download_original"],
    authentication: "oauth",
    icon: "folder",
    featureFlag: "FRAMEIO_CONNECTOR",
    supportsPublicLinks: true,
  }),
  define({
    id: "box",
    label: "Box",
    description: "Browse enterprise or personal Box files and import an authorised asset.",
    category: "cloud_storage",
    availability: "beta",
    capabilities: ["metadata", "browse", "search", "download_original"],
    authentication: "oauth",
    icon: "cloud",
    featureFlag: "BOX_CONNECTOR",
  }),
  define({
    id: "google_photos",
    label: "Google Photos",
    description: "Select specific media with Google's approved picker and limited scopes.",
    category: "cloud_storage",
    availability: "beta",
    capabilities: ["metadata", "browse", "download_original"],
    authentication: "oauth",
    icon: "cloud",
    featureFlag: "GOOGLE_PHOTOS_CONNECTOR",
  }),
  comingSoon(
    "twitch",
    "Twitch",
    "video_platforms",
    "Import authorised broadcasts and highlights when an official asset workflow is available.",
    "video",
  ),
  comingSoon(
    "kick",
    "Kick",
    "video_platforms",
    "Authorised creator media import is planned.",
    "video",
  ),
  comingSoon(
    "rumble",
    "Rumble",
    "video_platforms",
    "Official creator-library import is planned.",
    "video",
  ),
  comingSoon(
    "facebook",
    "Facebook",
    "video_platforms",
    "Page media import and publishing are planned through official APIs.",
    "video",
  ),
  comingSoon(
    "instagram",
    "Instagram",
    "video_platforms",
    "Professional account publishing is planned through official APIs.",
    "video",
  ),
  comingSoon(
    "tiktok",
    "TikTok",
    "video_platforms",
    "Official creator publishing is planned.",
    "video",
  ),
  comingSoon(
    "linkedin",
    "LinkedIn",
    "video_platforms",
    "Official organisation and profile publishing is planned.",
    "video",
  ),
  comingSoon("x", "X", "video_platforms", "Official media publishing is planned.", "video"),
  comingSoon(
    "streamyard",
    "StreamYard",
    "recording_platforms",
    "Recording export import is planned.",
    "recording",
  ),
  comingSoon(
    "medal",
    "Medal.tv",
    "video_platforms",
    "Authorised clip-library import is planned.",
    "video",
  ),
  comingSoon(
    "wistia",
    "Wistia",
    "video_platforms",
    "Project and media-library import is planned.",
    "video",
  ),
  comingSoon(
    "sproutvideo",
    "SproutVideo",
    "video_platforms",
    "Authorised library import is planned.",
    "video",
  ),
  comingSoon(
    "brightcove",
    "Brightcove",
    "video_platforms",
    "Enterprise video-library import is planned.",
    "video",
  ),
  comingSoon(
    "cloudflare_stream",
    "Cloudflare Stream",
    "video_platforms",
    "Authorised asset import is planned.",
    "video",
  ),
  comingSoon(
    "mux",
    "Mux",
    "video_platforms",
    "Asset and playback metadata integration is planned.",
    "video",
    "api_key",
  ),
  comingSoon(
    "vidyard",
    "Vidyard",
    "video_platforms",
    "Authorised library import is planned.",
    "video",
  ),
  comingSoon(
    "teams",
    "Microsoft Teams recordings",
    "recording_platforms",
    "Import through authorised OneDrive or SharePoint recordings is planned.",
    "recording",
  ),
  comingSoon(
    "google_meet",
    "Google Meet recordings",
    "recording_platforms",
    "Import authorised recordings from Drive is planned.",
    "recording",
  ),
  comingSoon(
    "descript",
    "Descript",
    "recording_platforms",
    "Project export import is planned.",
    "recording",
  ),
  comingSoon(
    "zencastr",
    "Zencastr",
    "recording_platforms",
    "Recording and transcript import is planned.",
    "recording",
  ),
  comingSoon(
    "squadcast",
    "SquadCast",
    "recording_platforms",
    "Recording export import is planned.",
    "recording",
  ),
  comingSoon(
    "restream",
    "Restream",
    "recording_platforms",
    "Recording library import is planned.",
    "recording",
  ),
  comingSoon(
    "podbean",
    "Podbean",
    "podcast_audio",
    "Podcast episode import is planned; public RSS already works.",
    "podcast",
  ),
  comingSoon(
    "buzzsprout",
    "Buzzsprout",
    "podcast_audio",
    "Podcast management integration is planned; public RSS already works.",
    "podcast",
  ),
  comingSoon(
    "transistor",
    "Transistor",
    "podcast_audio",
    "Podcast management integration is planned; public RSS already works.",
    "podcast",
  ),
  comingSoon(
    "captivate",
    "Captivate",
    "podcast_audio",
    "Podcast management integration is planned; public RSS already works.",
    "podcast",
  ),
  comingSoon(
    "spotify_creators",
    "Spotify for Creators",
    "podcast_audio",
    "Official creator integration is planned.",
    "podcast",
  ),
  comingSoon(
    "soundcloud",
    "SoundCloud",
    "podcast_audio",
    "Authorised creator-track import is planned.",
    "podcast",
  ),
  comingSoon(
    "adobe_cc",
    "Adobe Creative Cloud",
    "cloud_storage",
    "Creative Cloud asset import is planned.",
    "cloud",
  ),
  comingSoon(
    "canva",
    "Canva",
    "cloud_storage",
    "Authorised design export import is planned.",
    "cloud",
  ),
  comingSoon(
    "notion",
    "Notion file attachments",
    "cloud_storage",
    "Workspace attachment import is planned.",
    "folder",
  ),
  comingSoon(
    "slack",
    "Slack file attachments",
    "cloud_storage",
    "Workspace file import is planned.",
    "message",
  ),
  comingSoon(
    "discord",
    "Discord attachments",
    "cloud_storage",
    "Authorised attachment import is planned.",
    "message",
  ),
  comingSoon(
    "telegram",
    "Telegram file imports",
    "cloud_storage",
    "Authorised file import is planned.",
    "message",
  ),
  comingSoon(
    "ftp",
    "FTP",
    "developer_automation",
    "Credential-vault-backed file import is planned.",
    "database",
    "api_key",
  ),
  comingSoon(
    "sftp",
    "SFTP",
    "developer_automation",
    "Credential-vault-backed secure file import is planned.",
    "database",
    "api_key",
  ),
  comingSoon(
    "webdav",
    "WebDAV",
    "developer_automation",
    "Credential-vault-backed file import is planned.",
    "database",
    "api_key",
  ),
  comingSoon(
    "azure_blob",
    "Azure Blob Storage",
    "cloud_storage",
    "Signed object and managed identity import are planned.",
    "database",
    "signed_url",
  ),
  comingSoon(
    "gcs",
    "Google Cloud Storage",
    "cloud_storage",
    "Signed object import is planned.",
    "database",
    "signed_url",
  ),
  comingSoon(
    "bunny_stream",
    "Bunny Stream",
    "video_platforms",
    "Authorised video-library import is planned.",
    "video",
    "api_key",
  ),
  comingSoon(
    "wasabi",
    "Wasabi",
    "cloud_storage",
    "S3-compatible connection profiles are planned; signed URLs can use the S3 connector.",
    "database",
    "signed_url",
  ),
  comingSoon(
    "synology",
    "Synology",
    "cloud_storage",
    "Private NAS import is planned with explicit network controls.",
    "database",
    "api_key",
  ),
  comingSoon(
    "nextcloud",
    "Nextcloud",
    "cloud_storage",
    "Authorised WebDAV-backed import is planned.",
    "cloud",
  ),
  comingSoon(
    "rest_api",
    "REST API",
    "developer_automation",
    "Programmatic imports and job creation are planned after delivery logs and scoped keys ship.",
    "automation",
    "api_key",
  ),
  comingSoon(
    "webhooks",
    "Webhooks",
    "developer_automation",
    "Signed delivery events with retries and logs are planned.",
    "automation",
    "api_key",
  ),
  comingSoon(
    "zapier",
    "Zapier",
    "developer_automation",
    "Workflow automation is planned on top of signed webhooks and the REST API.",
    "automation",
  ),
  comingSoon(
    "make",
    "Make",
    "developer_automation",
    "Workflow automation is planned on top of signed webhooks and the REST API.",
    "automation",
  ),
  comingSoon(
    "n8n",
    "n8n",
    "developer_automation",
    "Workflow automation is planned on top of signed webhooks and the REST API.",
    "automation",
    "api_key",
  ),
  define({
    id: "other",
    label: "Other source",
    description: "Use an owner-controlled HTTPS media URL when no named connector matches.",
    category: "other",
    availability: "available",
    capabilities: ["metadata", "download_original"],
    authentication: "none",
    icon: "other",
    supportsPublicLinks: true,
    searchTerms: ["unknown", "generic"],
  }),
] as const satisfies readonly ConnectorDefinition[];

export type ConnectorId = (typeof CONNECTOR_REGISTRY)[number]["id"];

export function getConnector(id: string): ConnectorDefinition | undefined {
  return CONNECTOR_REGISTRY.find((connector) => connector.id === id);
}

const duplicateIds = CONNECTOR_REGISTRY.map((connector) => connector.id).filter(
  (id, index, ids) => ids.indexOf(id) !== index,
);
if (duplicateIds.length) throw new Error(`Duplicate connector ids: ${duplicateIds.join(", ")}`);
