/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeClipperRouteImport } from './routes/youtube-clipper'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AiTransparencyRouteImport } from './routes/ai-transparency'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UseCasesIndexRouteImport } from './routes/use-cases.index'
import { Route as UseCasesYoutubeRouteImport } from './routes/use-cases.youtube'
import { Route as UseCasesShortFormRouteImport } from './routes/use-cases.short-form'
import { Route as UseCasesProductDemosRouteImport } from './routes/use-cases.product-demos'
import { Route as UseCasesPodcastsRouteImport } from './routes/use-cases.podcasts'
import { Route as UseCasesCoursesRouteImport } from './routes/use-cases.courses'
import { Route as DocsUploadingMediaRouteImport } from './routes/docs.uploading-media'
import { Route as DocsTimelineRouteImport } from './routes/docs.timeline'
import { Route as DocsGettingStartedRouteImport } from './routes/docs.getting-started'
import { Route as DocsExportingRouteImport } from './routes/docs.exporting'
import { Route as DocsAiEditorRouteImport } from './routes/docs.ai-editor'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthYoutubeCallbackRouteImport } from './routes/auth.youtube.callback'
import { Route as AuthenticatedAppYoutubeClipperRouteImport } from './routes/_authenticated.app.youtube-clipper'
import { Route as AuthenticatedAppUsageRouteImport } from './routes/_authenticated.app.usage'
import { Route as AuthenticatedAppUploadsRouteImport } from './routes/_authenticated.app.uploads'
import { Route as AuthenticatedAppTemplatesRouteImport } from './routes/_authenticated.app.templates'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated.app.settings'
import { Route as AuthenticatedAppHelpRouteImport } from './routes/_authenticated.app.help'
import { Route as AuthenticatedAppFeedbackRouteImport } from './routes/_authenticated.app.feedback'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated.app.billing'
import { Route as AuthenticatedAppYoutubeClipperIndexRouteImport } from './routes/_authenticated.app.youtube-clipper.index'
import { Route as AuthenticatedAppSettingsIndexRouteImport } from './routes/_authenticated.app.settings.index'
import { Route as AuthenticatedAppProjectsIndexRouteImport } from './routes/_authenticated.app.projects.index'
import { Route as AuthenticatedAppYoutubeClipperNewRouteImport } from './routes/_authenticated.app.youtube-clipper.new'
import { Route as AuthenticatedAppSettingsPrivacyRouteImport } from './routes/_authenticated.app.settings.privacy'
import { Route as AuthenticatedAppSettingsPreferencesRouteImport } from './routes/_authenticated.app.settings.preferences'
import { Route as AuthenticatedAppSettingsNotificationsRouteImport } from './routes/_authenticated.app.settings.notifications'
import { Route as AuthenticatedAppSettingsIntegrationsRouteImport } from './routes/_authenticated.app.settings.integrations'
import { Route as AuthenticatedAppProjectsNewRouteImport } from './routes/_authenticated.app.projects.new'
import { Route as AuthenticatedAppProjectsProjectIdRouteImport } from './routes/_authenticated.app.projects.$projectId'
import { Route as AuthenticatedAppProjectsProjectIdIndexRouteImport } from './routes/_authenticated.app.projects.$projectId.index'
import { Route as AuthenticatedAppYoutubeClipperJobsJobIdRouteImport } from './routes/_authenticated.app.youtube-clipper.jobs.$jobId'
import { Route as AuthenticatedAppProjectsProjectIdVersionsRouteImport } from './routes/_authenticated.app.projects.$projectId.versions'
import { Route as AuthenticatedAppProjectsProjectIdTranscriptRouteImport } from './routes/_authenticated.app.projects.$projectId.transcript'
import { Route as AuthenticatedAppProjectsProjectIdMediaRouteImport } from './routes/_authenticated.app.projects.$projectId.media'
import { Route as AuthenticatedAppProjectsProjectIdExportsRouteImport } from './routes/_authenticated.app.projects.$projectId.exports'
import { Route as AuthenticatedAppProjectsProjectIdEditorRouteImport } from './routes/_authenticated.app.projects.$projectId.editor'
import { Route as AuthenticatedAppYoutubeClipperClipsClipIdEditRouteImport } from './routes/_authenticated.app.youtube-clipper.clips.$clipId.edit'

const YoutubeClipperRoute = YoutubeClipperRouteImport.update({
  id: '/youtube-clipper',
  path: '/youtube-clipper',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTransparencyRoute = AiTransparencyRouteImport.update({
  id: '/ai-transparency',
  path: '/ai-transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesIndexRoute = UseCasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UseCasesRoute,
} as any)
const UseCasesYoutubeRoute = UseCasesYoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => UseCasesRoute,
} as any)
const UseCasesShortFormRoute = UseCasesShortFormRouteImport.update({
  id: '/short-form',
  path: '/short-form',
  getParentRoute: () => UseCasesRoute,
} as any)
const UseCasesProductDemosRoute = UseCasesProductDemosRouteImport.update({
  id: '/product-demos',
  path: '/product-demos',
  getParentRoute: () => UseCasesRoute,
} as any)
const UseCasesPodcastsRoute = UseCasesPodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => UseCasesRoute,
} as any)
const UseCasesCoursesRoute = UseCasesCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => UseCasesRoute,
} as any)
const DocsUploadingMediaRoute = DocsUploadingMediaRouteImport.update({
  id: '/uploading-media',
  path: '/uploading-media',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTimelineRoute = DocsTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsExportingRoute = DocsExportingRouteImport.update({
  id: '/exporting',
  path: '/exporting',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAiEditorRoute = DocsAiEditorRouteImport.update({
  id: '/ai-editor',
  path: '/ai-editor',
  getParentRoute: () => DocsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthYoutubeCallbackRoute = AuthYoutubeCallbackRouteImport.update({
  id: '/auth/youtube/callback',
  path: '/auth/youtube/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppYoutubeClipperRoute =
  AuthenticatedAppYoutubeClipperRouteImport.update({
    id: '/youtube-clipper',
    path: '/youtube-clipper',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppUsageRoute = AuthenticatedAppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppUploadsRoute = AuthenticatedAppUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTemplatesRoute =
  AuthenticatedAppTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHelpRoute = AuthenticatedAppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFeedbackRoute =
  AuthenticatedAppFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppYoutubeClipperIndexRoute =
  AuthenticatedAppYoutubeClipperIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppYoutubeClipperRoute,
  } as any)
const AuthenticatedAppSettingsIndexRoute =
  AuthenticatedAppSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppProjectsIndexRoute =
  AuthenticatedAppProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppYoutubeClipperNewRoute =
  AuthenticatedAppYoutubeClipperNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAppYoutubeClipperRoute,
  } as any)
const AuthenticatedAppSettingsPrivacyRoute =
  AuthenticatedAppSettingsPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsPreferencesRoute =
  AuthenticatedAppSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsNotificationsRoute =
  AuthenticatedAppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsIntegrationsRoute =
  AuthenticatedAppSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppProjectsNewRoute =
  AuthenticatedAppProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProjectsProjectIdRoute =
  AuthenticatedAppProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProjectsProjectIdIndexRoute =
  AuthenticatedAppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppProjectsProjectIdRoute,
  } as any)
const AuthenticatedAppYoutubeClipperJobsJobIdRoute =
  AuthenticatedAppYoutubeClipperJobsJobIdRouteImport.update({
    id: '/jobs/$jobId',
    path: '/jobs/$jobId',
    getParentRoute: () => AuthenticatedAppYoutubeClipperRoute,
  } as any)
const AuthenticatedAppProjectsProjectIdVersionsRoute =
  AuthenticatedAppProjectsProjectIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => AuthenticatedAppProjectsProjectIdRoute,
  } as any)
const AuthenticatedAppProjectsProjectIdTranscriptRoute =
  AuthenticatedAppProjectsProjectIdTranscriptRouteImport.update({
    id: '/transcript',
    path: '/transcript',
    getParentRoute: () => AuthenticatedAppProjectsProjectIdRoute,
  } as any)
const AuthenticatedAppProjectsProjectIdMediaRoute =
  AuthenticatedAppProjectsProjectIdMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedAppProjectsProjectIdRoute,
  } as any)
const AuthenticatedAppProjectsProjectIdExportsRoute =
  AuthenticatedAppProjectsProjectIdExportsRouteImport.update({
    id: '/exports',
    path: '/exports',
    getParentRoute: () => AuthenticatedAppProjectsProjectIdRoute,
  } as any)
const AuthenticatedAppProjectsProjectIdEditorRoute =
  AuthenticatedAppProjectsProjectIdEditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => AuthenticatedAppProjectsProjectIdRoute,
  } as any)
const AuthenticatedAppYoutubeClipperClipsClipIdEditRoute =
  AuthenticatedAppYoutubeClipperClipsClipIdEditRouteImport.update({
    id: '/clips/$clipId/edit',
    path: '/clips/$clipId/edit',
    getParentRoute: () => AuthenticatedAppYoutubeClipperRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/ai-transparency': typeof AiTransparencyRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/copyright': typeof CopyrightRoute
  '/design-system': typeof DesignSystemRoute
  '/docs': typeof DocsRouteWithChildren
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/youtube-clipper': typeof YoutubeClipperRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/docs/ai-editor': typeof DocsAiEditorRoute
  '/docs/exporting': typeof DocsExportingRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/timeline': typeof DocsTimelineRoute
  '/docs/uploading-media': typeof DocsUploadingMediaRoute
  '/use-cases/courses': typeof UseCasesCoursesRoute
  '/use-cases/podcasts': typeof UseCasesPodcastsRoute
  '/use-cases/product-demos': typeof UseCasesProductDemosRoute
  '/use-cases/short-form': typeof UseCasesShortFormRoute
  '/use-cases/youtube': typeof UseCasesYoutubeRoute
  '/use-cases/': typeof UseCasesIndexRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/feedback': typeof AuthenticatedAppFeedbackRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app/uploads': typeof AuthenticatedAppUploadsRoute
  '/app/usage': typeof AuthenticatedAppUsageRoute
  '/app/youtube-clipper': typeof AuthenticatedAppYoutubeClipperRouteWithChildren
  '/auth/youtube/callback': typeof AuthYoutubeCallbackRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/projects/$projectId': typeof AuthenticatedAppProjectsProjectIdRouteWithChildren
  '/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/app/settings/integrations': typeof AuthenticatedAppSettingsIntegrationsRoute
  '/app/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/app/settings/preferences': typeof AuthenticatedAppSettingsPreferencesRoute
  '/app/settings/privacy': typeof AuthenticatedAppSettingsPrivacyRoute
  '/app/youtube-clipper/new': typeof AuthenticatedAppYoutubeClipperNewRoute
  '/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/app/youtube-clipper/': typeof AuthenticatedAppYoutubeClipperIndexRoute
  '/app/projects/$projectId/editor': typeof AuthenticatedAppProjectsProjectIdEditorRoute
  '/app/projects/$projectId/exports': typeof AuthenticatedAppProjectsProjectIdExportsRoute
  '/app/projects/$projectId/media': typeof AuthenticatedAppProjectsProjectIdMediaRoute
  '/app/projects/$projectId/transcript': typeof AuthenticatedAppProjectsProjectIdTranscriptRoute
  '/app/projects/$projectId/versions': typeof AuthenticatedAppProjectsProjectIdVersionsRoute
  '/app/youtube-clipper/jobs/$jobId': typeof AuthenticatedAppYoutubeClipperJobsJobIdRoute
  '/app/projects/$projectId/': typeof AuthenticatedAppProjectsProjectIdIndexRoute
  '/app/youtube-clipper/clips/$clipId/edit': typeof AuthenticatedAppYoutubeClipperClipsClipIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/ai-transparency': typeof AiTransparencyRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/copyright': typeof CopyrightRoute
  '/design-system': typeof DesignSystemRoute
  '/docs': typeof DocsRouteWithChildren
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/youtube-clipper': typeof YoutubeClipperRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/docs/ai-editor': typeof DocsAiEditorRoute
  '/docs/exporting': typeof DocsExportingRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/timeline': typeof DocsTimelineRoute
  '/docs/uploading-media': typeof DocsUploadingMediaRoute
  '/use-cases/courses': typeof UseCasesCoursesRoute
  '/use-cases/podcasts': typeof UseCasesPodcastsRoute
  '/use-cases/product-demos': typeof UseCasesProductDemosRoute
  '/use-cases/short-form': typeof UseCasesShortFormRoute
  '/use-cases/youtube': typeof UseCasesYoutubeRoute
  '/use-cases': typeof UseCasesIndexRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/feedback': typeof AuthenticatedAppFeedbackRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/app/uploads': typeof AuthenticatedAppUploadsRoute
  '/app/usage': typeof AuthenticatedAppUsageRoute
  '/auth/youtube/callback': typeof AuthYoutubeCallbackRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/app/settings/integrations': typeof AuthenticatedAppSettingsIntegrationsRoute
  '/app/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/app/settings/preferences': typeof AuthenticatedAppSettingsPreferencesRoute
  '/app/settings/privacy': typeof AuthenticatedAppSettingsPrivacyRoute
  '/app/youtube-clipper/new': typeof AuthenticatedAppYoutubeClipperNewRoute
  '/app/projects': typeof AuthenticatedAppProjectsIndexRoute
  '/app/settings': typeof AuthenticatedAppSettingsIndexRoute
  '/app/youtube-clipper': typeof AuthenticatedAppYoutubeClipperIndexRoute
  '/app/projects/$projectId/editor': typeof AuthenticatedAppProjectsProjectIdEditorRoute
  '/app/projects/$projectId/exports': typeof AuthenticatedAppProjectsProjectIdExportsRoute
  '/app/projects/$projectId/media': typeof AuthenticatedAppProjectsProjectIdMediaRoute
  '/app/projects/$projectId/transcript': typeof AuthenticatedAppProjectsProjectIdTranscriptRoute
  '/app/projects/$projectId/versions': typeof AuthenticatedAppProjectsProjectIdVersionsRoute
  '/app/youtube-clipper/jobs/$jobId': typeof AuthenticatedAppYoutubeClipperJobsJobIdRoute
  '/app/projects/$projectId': typeof AuthenticatedAppProjectsProjectIdIndexRoute
  '/app/youtube-clipper/clips/$clipId/edit': typeof AuthenticatedAppYoutubeClipperClipsClipIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/acceptable-use': typeof AcceptableUseRoute
  '/ai-transparency': typeof AiTransparencyRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/copyright': typeof CopyrightRoute
  '/design-system': typeof DesignSystemRoute
  '/docs': typeof DocsRouteWithChildren
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/imprint': typeof ImprintRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/use-cases': typeof UseCasesRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/youtube-clipper': typeof YoutubeClipperRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/docs/ai-editor': typeof DocsAiEditorRoute
  '/docs/exporting': typeof DocsExportingRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/timeline': typeof DocsTimelineRoute
  '/docs/uploading-media': typeof DocsUploadingMediaRoute
  '/use-cases/courses': typeof UseCasesCoursesRoute
  '/use-cases/podcasts': typeof UseCasesPodcastsRoute
  '/use-cases/product-demos': typeof UseCasesProductDemosRoute
  '/use-cases/short-form': typeof UseCasesShortFormRoute
  '/use-cases/youtube': typeof UseCasesYoutubeRoute
  '/use-cases/': typeof UseCasesIndexRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/feedback': typeof AuthenticatedAppFeedbackRoute
  '/_authenticated/app/help': typeof AuthenticatedAppHelpRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/_authenticated/app/templates': typeof AuthenticatedAppTemplatesRoute
  '/_authenticated/app/uploads': typeof AuthenticatedAppUploadsRoute
  '/_authenticated/app/usage': typeof AuthenticatedAppUsageRoute
  '/_authenticated/app/youtube-clipper': typeof AuthenticatedAppYoutubeClipperRouteWithChildren
  '/auth/youtube/callback': typeof AuthYoutubeCallbackRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/projects/$projectId': typeof AuthenticatedAppProjectsProjectIdRouteWithChildren
  '/_authenticated/app/projects/new': typeof AuthenticatedAppProjectsNewRoute
  '/_authenticated/app/settings/integrations': typeof AuthenticatedAppSettingsIntegrationsRoute
  '/_authenticated/app/settings/notifications': typeof AuthenticatedAppSettingsNotificationsRoute
  '/_authenticated/app/settings/preferences': typeof AuthenticatedAppSettingsPreferencesRoute
  '/_authenticated/app/settings/privacy': typeof AuthenticatedAppSettingsPrivacyRoute
  '/_authenticated/app/youtube-clipper/new': typeof AuthenticatedAppYoutubeClipperNewRoute
  '/_authenticated/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/_authenticated/app/settings/': typeof AuthenticatedAppSettingsIndexRoute
  '/_authenticated/app/youtube-clipper/': typeof AuthenticatedAppYoutubeClipperIndexRoute
  '/_authenticated/app/projects/$projectId/editor': typeof AuthenticatedAppProjectsProjectIdEditorRoute
  '/_authenticated/app/projects/$projectId/exports': typeof AuthenticatedAppProjectsProjectIdExportsRoute
  '/_authenticated/app/projects/$projectId/media': typeof AuthenticatedAppProjectsProjectIdMediaRoute
  '/_authenticated/app/projects/$projectId/transcript': typeof AuthenticatedAppProjectsProjectIdTranscriptRoute
  '/_authenticated/app/projects/$projectId/versions': typeof AuthenticatedAppProjectsProjectIdVersionsRoute
  '/_authenticated/app/youtube-clipper/jobs/$jobId': typeof AuthenticatedAppYoutubeClipperJobsJobIdRoute
  '/_authenticated/app/projects/$projectId/': typeof AuthenticatedAppProjectsProjectIdIndexRoute
  '/_authenticated/app/youtube-clipper/clips/$clipId/edit': typeof AuthenticatedAppYoutubeClipperClipsClipIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceptable-use'
    | '/ai-transparency'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/copyright'
    | '/design-system'
    | '/docs'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/imprint'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/roadmap'
    | '/security'
    | '/signup'
    | '/status'
    | '/terms'
    | '/use-cases'
    | '/verify-email'
    | '/youtube-clipper'
    | '/app'
    | '/auth/callback'
    | '/docs/ai-editor'
    | '/docs/exporting'
    | '/docs/getting-started'
    | '/docs/timeline'
    | '/docs/uploading-media'
    | '/use-cases/courses'
    | '/use-cases/podcasts'
    | '/use-cases/product-demos'
    | '/use-cases/short-form'
    | '/use-cases/youtube'
    | '/use-cases/'
    | '/app/billing'
    | '/app/feedback'
    | '/app/help'
    | '/app/settings'
    | '/app/templates'
    | '/app/uploads'
    | '/app/usage'
    | '/app/youtube-clipper'
    | '/auth/youtube/callback'
    | '/app/'
    | '/app/projects/$projectId'
    | '/app/projects/new'
    | '/app/settings/integrations'
    | '/app/settings/notifications'
    | '/app/settings/preferences'
    | '/app/settings/privacy'
    | '/app/youtube-clipper/new'
    | '/app/projects/'
    | '/app/settings/'
    | '/app/youtube-clipper/'
    | '/app/projects/$projectId/editor'
    | '/app/projects/$projectId/exports'
    | '/app/projects/$projectId/media'
    | '/app/projects/$projectId/transcript'
    | '/app/projects/$projectId/versions'
    | '/app/youtube-clipper/jobs/$jobId'
    | '/app/projects/$projectId/'
    | '/app/youtube-clipper/clips/$clipId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceptable-use'
    | '/ai-transparency'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/copyright'
    | '/design-system'
    | '/docs'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/imprint'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/roadmap'
    | '/security'
    | '/signup'
    | '/status'
    | '/terms'
    | '/verify-email'
    | '/youtube-clipper'
    | '/auth/callback'
    | '/docs/ai-editor'
    | '/docs/exporting'
    | '/docs/getting-started'
    | '/docs/timeline'
    | '/docs/uploading-media'
    | '/use-cases/courses'
    | '/use-cases/podcasts'
    | '/use-cases/product-demos'
    | '/use-cases/short-form'
    | '/use-cases/youtube'
    | '/use-cases'
    | '/app/billing'
    | '/app/feedback'
    | '/app/help'
    | '/app/templates'
    | '/app/uploads'
    | '/app/usage'
    | '/auth/youtube/callback'
    | '/app'
    | '/app/projects/new'
    | '/app/settings/integrations'
    | '/app/settings/notifications'
    | '/app/settings/preferences'
    | '/app/settings/privacy'
    | '/app/youtube-clipper/new'
    | '/app/projects'
    | '/app/settings'
    | '/app/youtube-clipper'
    | '/app/projects/$projectId/editor'
    | '/app/projects/$projectId/exports'
    | '/app/projects/$projectId/media'
    | '/app/projects/$projectId/transcript'
    | '/app/projects/$projectId/versions'
    | '/app/youtube-clipper/jobs/$jobId'
    | '/app/projects/$projectId'
    | '/app/youtube-clipper/clips/$clipId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acceptable-use'
    | '/ai-transparency'
    | '/changelog'
    | '/contact'
    | '/cookies'
    | '/copyright'
    | '/design-system'
    | '/docs'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/imprint'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/roadmap'
    | '/security'
    | '/signup'
    | '/status'
    | '/terms'
    | '/use-cases'
    | '/verify-email'
    | '/youtube-clipper'
    | '/_authenticated/app'
    | '/auth/callback'
    | '/docs/ai-editor'
    | '/docs/exporting'
    | '/docs/getting-started'
    | '/docs/timeline'
    | '/docs/uploading-media'
    | '/use-cases/courses'
    | '/use-cases/podcasts'
    | '/use-cases/product-demos'
    | '/use-cases/short-form'
    | '/use-cases/youtube'
    | '/use-cases/'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/feedback'
    | '/_authenticated/app/help'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/templates'
    | '/_authenticated/app/uploads'
    | '/_authenticated/app/usage'
    | '/_authenticated/app/youtube-clipper'
    | '/auth/youtube/callback'
    | '/_authenticated/app/'
    | '/_authenticated/app/projects/$projectId'
    | '/_authenticated/app/projects/new'
    | '/_authenticated/app/settings/integrations'
    | '/_authenticated/app/settings/notifications'
    | '/_authenticated/app/settings/preferences'
    | '/_authenticated/app/settings/privacy'
    | '/_authenticated/app/youtube-clipper/new'
    | '/_authenticated/app/projects/'
    | '/_authenticated/app/settings/'
    | '/_authenticated/app/youtube-clipper/'
    | '/_authenticated/app/projects/$projectId/editor'
    | '/_authenticated/app/projects/$projectId/exports'
    | '/_authenticated/app/projects/$projectId/media'
    | '/_authenticated/app/projects/$projectId/transcript'
    | '/_authenticated/app/projects/$projectId/versions'
    | '/_authenticated/app/youtube-clipper/jobs/$jobId'
    | '/_authenticated/app/projects/$projectId/'
    | '/_authenticated/app/youtube-clipper/clips/$clipId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptableUseRoute: typeof AcceptableUseRoute
  AiTransparencyRoute: typeof AiTransparencyRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CopyrightRoute: typeof CopyrightRoute
  DesignSystemRoute: typeof DesignSystemRoute
  DocsRoute: typeof DocsRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ImprintRoute: typeof ImprintRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoadmapRoute: typeof RoadmapRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  UseCasesRoute: typeof UseCasesRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
  YoutubeClipperRoute: typeof YoutubeClipperRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthYoutubeCallbackRoute: typeof AuthYoutubeCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube-clipper': {
      id: '/youtube-clipper'
      path: '/youtube-clipper'
      fullPath: '/youtube-clipper'
      preLoaderRoute: typeof YoutubeClipperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-transparency': {
      id: '/ai-transparency'
      path: '/ai-transparency'
      fullPath: '/ai-transparency'
      preLoaderRoute: typeof AiTransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/': {
      id: '/use-cases/'
      path: '/'
      fullPath: '/use-cases/'
      preLoaderRoute: typeof UseCasesIndexRouteImport
      parentRoute: typeof UseCasesRoute
    }
    '/use-cases/youtube': {
      id: '/use-cases/youtube'
      path: '/youtube'
      fullPath: '/use-cases/youtube'
      preLoaderRoute: typeof UseCasesYoutubeRouteImport
      parentRoute: typeof UseCasesRoute
    }
    '/use-cases/short-form': {
      id: '/use-cases/short-form'
      path: '/short-form'
      fullPath: '/use-cases/short-form'
      preLoaderRoute: typeof UseCasesShortFormRouteImport
      parentRoute: typeof UseCasesRoute
    }
    '/use-cases/product-demos': {
      id: '/use-cases/product-demos'
      path: '/product-demos'
      fullPath: '/use-cases/product-demos'
      preLoaderRoute: typeof UseCasesProductDemosRouteImport
      parentRoute: typeof UseCasesRoute
    }
    '/use-cases/podcasts': {
      id: '/use-cases/podcasts'
      path: '/podcasts'
      fullPath: '/use-cases/podcasts'
      preLoaderRoute: typeof UseCasesPodcastsRouteImport
      parentRoute: typeof UseCasesRoute
    }
    '/use-cases/courses': {
      id: '/use-cases/courses'
      path: '/courses'
      fullPath: '/use-cases/courses'
      preLoaderRoute: typeof UseCasesCoursesRouteImport
      parentRoute: typeof UseCasesRoute
    }
    '/docs/uploading-media': {
      id: '/docs/uploading-media'
      path: '/uploading-media'
      fullPath: '/docs/uploading-media'
      preLoaderRoute: typeof DocsUploadingMediaRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/timeline': {
      id: '/docs/timeline'
      path: '/timeline'
      fullPath: '/docs/timeline'
      preLoaderRoute: typeof DocsTimelineRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/exporting': {
      id: '/docs/exporting'
      path: '/exporting'
      fullPath: '/docs/exporting'
      preLoaderRoute: typeof DocsExportingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/ai-editor': {
      id: '/docs/ai-editor'
      path: '/ai-editor'
      fullPath: '/docs/ai-editor'
      preLoaderRoute: typeof DocsAiEditorRouteImport
      parentRoute: typeof DocsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/auth/youtube/callback': {
      id: '/auth/youtube/callback'
      path: '/auth/youtube/callback'
      fullPath: '/auth/youtube/callback'
      preLoaderRoute: typeof AuthYoutubeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/youtube-clipper': {
      id: '/_authenticated/app/youtube-clipper'
      path: '/youtube-clipper'
      fullPath: '/app/youtube-clipper'
      preLoaderRoute: typeof AuthenticatedAppYoutubeClipperRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/usage': {
      id: '/_authenticated/app/usage'
      path: '/usage'
      fullPath: '/app/usage'
      preLoaderRoute: typeof AuthenticatedAppUsageRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/uploads': {
      id: '/_authenticated/app/uploads'
      path: '/uploads'
      fullPath: '/app/uploads'
      preLoaderRoute: typeof AuthenticatedAppUploadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/templates': {
      id: '/_authenticated/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AuthenticatedAppTemplatesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/help': {
      id: '/_authenticated/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AuthenticatedAppHelpRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/feedback': {
      id: '/_authenticated/app/feedback'
      path: '/feedback'
      fullPath: '/app/feedback'
      preLoaderRoute: typeof AuthenticatedAppFeedbackRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/youtube-clipper/': {
      id: '/_authenticated/app/youtube-clipper/'
      path: '/'
      fullPath: '/app/youtube-clipper/'
      preLoaderRoute: typeof AuthenticatedAppYoutubeClipperIndexRouteImport
      parentRoute: typeof AuthenticatedAppYoutubeClipperRoute
    }
    '/_authenticated/app/settings/': {
      id: '/_authenticated/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AuthenticatedAppSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/projects/': {
      id: '/_authenticated/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AuthenticatedAppProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/youtube-clipper/new': {
      id: '/_authenticated/app/youtube-clipper/new'
      path: '/new'
      fullPath: '/app/youtube-clipper/new'
      preLoaderRoute: typeof AuthenticatedAppYoutubeClipperNewRouteImport
      parentRoute: typeof AuthenticatedAppYoutubeClipperRoute
    }
    '/_authenticated/app/settings/privacy': {
      id: '/_authenticated/app/settings/privacy'
      path: '/privacy'
      fullPath: '/app/settings/privacy'
      preLoaderRoute: typeof AuthenticatedAppSettingsPrivacyRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/preferences': {
      id: '/_authenticated/app/settings/preferences'
      path: '/preferences'
      fullPath: '/app/settings/preferences'
      preLoaderRoute: typeof AuthenticatedAppSettingsPreferencesRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/notifications': {
      id: '/_authenticated/app/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AuthenticatedAppSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/integrations': {
      id: '/_authenticated/app/settings/integrations'
      path: '/integrations'
      fullPath: '/app/settings/integrations'
      preLoaderRoute: typeof AuthenticatedAppSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/projects/new': {
      id: '/_authenticated/app/projects/new'
      path: '/projects/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AuthenticatedAppProjectsNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/projects/$projectId': {
      id: '/_authenticated/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedAppProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/projects/$projectId/': {
      id: '/_authenticated/app/projects/$projectId/'
      path: '/'
      fullPath: '/app/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedAppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppProjectsProjectIdRoute
    }
    '/_authenticated/app/youtube-clipper/jobs/$jobId': {
      id: '/_authenticated/app/youtube-clipper/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/app/youtube-clipper/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedAppYoutubeClipperJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedAppYoutubeClipperRoute
    }
    '/_authenticated/app/projects/$projectId/versions': {
      id: '/_authenticated/app/projects/$projectId/versions'
      path: '/versions'
      fullPath: '/app/projects/$projectId/versions'
      preLoaderRoute: typeof AuthenticatedAppProjectsProjectIdVersionsRouteImport
      parentRoute: typeof AuthenticatedAppProjectsProjectIdRoute
    }
    '/_authenticated/app/projects/$projectId/transcript': {
      id: '/_authenticated/app/projects/$projectId/transcript'
      path: '/transcript'
      fullPath: '/app/projects/$projectId/transcript'
      preLoaderRoute: typeof AuthenticatedAppProjectsProjectIdTranscriptRouteImport
      parentRoute: typeof AuthenticatedAppProjectsProjectIdRoute
    }
    '/_authenticated/app/projects/$projectId/media': {
      id: '/_authenticated/app/projects/$projectId/media'
      path: '/media'
      fullPath: '/app/projects/$projectId/media'
      preLoaderRoute: typeof AuthenticatedAppProjectsProjectIdMediaRouteImport
      parentRoute: typeof AuthenticatedAppProjectsProjectIdRoute
    }
    '/_authenticated/app/projects/$projectId/exports': {
      id: '/_authenticated/app/projects/$projectId/exports'
      path: '/exports'
      fullPath: '/app/projects/$projectId/exports'
      preLoaderRoute: typeof AuthenticatedAppProjectsProjectIdExportsRouteImport
      parentRoute: typeof AuthenticatedAppProjectsProjectIdRoute
    }
    '/_authenticated/app/projects/$projectId/editor': {
      id: '/_authenticated/app/projects/$projectId/editor'
      path: '/editor'
      fullPath: '/app/projects/$projectId/editor'
      preLoaderRoute: typeof AuthenticatedAppProjectsProjectIdEditorRouteImport
      parentRoute: typeof AuthenticatedAppProjectsProjectIdRoute
    }
    '/_authenticated/app/youtube-clipper/clips/$clipId/edit': {
      id: '/_authenticated/app/youtube-clipper/clips/$clipId/edit'
      path: '/clips/$clipId/edit'
      fullPath: '/app/youtube-clipper/clips/$clipId/edit'
      preLoaderRoute: typeof AuthenticatedAppYoutubeClipperClipsClipIdEditRouteImport
      parentRoute: typeof AuthenticatedAppYoutubeClipperRoute
    }
  }
}

interface AuthenticatedAppSettingsRouteChildren {
  AuthenticatedAppSettingsIntegrationsRoute: typeof AuthenticatedAppSettingsIntegrationsRoute
  AuthenticatedAppSettingsNotificationsRoute: typeof AuthenticatedAppSettingsNotificationsRoute
  AuthenticatedAppSettingsPreferencesRoute: typeof AuthenticatedAppSettingsPreferencesRoute
  AuthenticatedAppSettingsPrivacyRoute: typeof AuthenticatedAppSettingsPrivacyRoute
  AuthenticatedAppSettingsIndexRoute: typeof AuthenticatedAppSettingsIndexRoute
}

const AuthenticatedAppSettingsRouteChildren: AuthenticatedAppSettingsRouteChildren =
  {
    AuthenticatedAppSettingsIntegrationsRoute:
      AuthenticatedAppSettingsIntegrationsRoute,
    AuthenticatedAppSettingsNotificationsRoute:
      AuthenticatedAppSettingsNotificationsRoute,
    AuthenticatedAppSettingsPreferencesRoute:
      AuthenticatedAppSettingsPreferencesRoute,
    AuthenticatedAppSettingsPrivacyRoute: AuthenticatedAppSettingsPrivacyRoute,
    AuthenticatedAppSettingsIndexRoute: AuthenticatedAppSettingsIndexRoute,
  }

const AuthenticatedAppSettingsRouteWithChildren =
  AuthenticatedAppSettingsRoute._addFileChildren(
    AuthenticatedAppSettingsRouteChildren,
  )

interface AuthenticatedAppYoutubeClipperRouteChildren {
  AuthenticatedAppYoutubeClipperNewRoute: typeof AuthenticatedAppYoutubeClipperNewRoute
  AuthenticatedAppYoutubeClipperIndexRoute: typeof AuthenticatedAppYoutubeClipperIndexRoute
  AuthenticatedAppYoutubeClipperJobsJobIdRoute: typeof AuthenticatedAppYoutubeClipperJobsJobIdRoute
  AuthenticatedAppYoutubeClipperClipsClipIdEditRoute: typeof AuthenticatedAppYoutubeClipperClipsClipIdEditRoute
}

const AuthenticatedAppYoutubeClipperRouteChildren: AuthenticatedAppYoutubeClipperRouteChildren =
  {
    AuthenticatedAppYoutubeClipperNewRoute:
      AuthenticatedAppYoutubeClipperNewRoute,
    AuthenticatedAppYoutubeClipperIndexRoute:
      AuthenticatedAppYoutubeClipperIndexRoute,
    AuthenticatedAppYoutubeClipperJobsJobIdRoute:
      AuthenticatedAppYoutubeClipperJobsJobIdRoute,
    AuthenticatedAppYoutubeClipperClipsClipIdEditRoute:
      AuthenticatedAppYoutubeClipperClipsClipIdEditRoute,
  }

const AuthenticatedAppYoutubeClipperRouteWithChildren =
  AuthenticatedAppYoutubeClipperRoute._addFileChildren(
    AuthenticatedAppYoutubeClipperRouteChildren,
  )

interface AuthenticatedAppProjectsProjectIdRouteChildren {
  AuthenticatedAppProjectsProjectIdEditorRoute: typeof AuthenticatedAppProjectsProjectIdEditorRoute
  AuthenticatedAppProjectsProjectIdExportsRoute: typeof AuthenticatedAppProjectsProjectIdExportsRoute
  AuthenticatedAppProjectsProjectIdMediaRoute: typeof AuthenticatedAppProjectsProjectIdMediaRoute
  AuthenticatedAppProjectsProjectIdTranscriptRoute: typeof AuthenticatedAppProjectsProjectIdTranscriptRoute
  AuthenticatedAppProjectsProjectIdVersionsRoute: typeof AuthenticatedAppProjectsProjectIdVersionsRoute
  AuthenticatedAppProjectsProjectIdIndexRoute: typeof AuthenticatedAppProjectsProjectIdIndexRoute
}

const AuthenticatedAppProjectsProjectIdRouteChildren: AuthenticatedAppProjectsProjectIdRouteChildren =
  {
    AuthenticatedAppProjectsProjectIdEditorRoute:
      AuthenticatedAppProjectsProjectIdEditorRoute,
    AuthenticatedAppProjectsProjectIdExportsRoute:
      AuthenticatedAppProjectsProjectIdExportsRoute,
    AuthenticatedAppProjectsProjectIdMediaRoute:
      AuthenticatedAppProjectsProjectIdMediaRoute,
    AuthenticatedAppProjectsProjectIdTranscriptRoute:
      AuthenticatedAppProjectsProjectIdTranscriptRoute,
    AuthenticatedAppProjectsProjectIdVersionsRoute:
      AuthenticatedAppProjectsProjectIdVersionsRoute,
    AuthenticatedAppProjectsProjectIdIndexRoute:
      AuthenticatedAppProjectsProjectIdIndexRoute,
  }

const AuthenticatedAppProjectsProjectIdRouteWithChildren =
  AuthenticatedAppProjectsProjectIdRoute._addFileChildren(
    AuthenticatedAppProjectsProjectIdRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppFeedbackRoute: typeof AuthenticatedAppFeedbackRoute
  AuthenticatedAppHelpRoute: typeof AuthenticatedAppHelpRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRouteWithChildren
  AuthenticatedAppTemplatesRoute: typeof AuthenticatedAppTemplatesRoute
  AuthenticatedAppUploadsRoute: typeof AuthenticatedAppUploadsRoute
  AuthenticatedAppUsageRoute: typeof AuthenticatedAppUsageRoute
  AuthenticatedAppYoutubeClipperRoute: typeof AuthenticatedAppYoutubeClipperRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppProjectsProjectIdRoute: typeof AuthenticatedAppProjectsProjectIdRouteWithChildren
  AuthenticatedAppProjectsNewRoute: typeof AuthenticatedAppProjectsNewRoute
  AuthenticatedAppProjectsIndexRoute: typeof AuthenticatedAppProjectsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppFeedbackRoute: AuthenticatedAppFeedbackRoute,
  AuthenticatedAppHelpRoute: AuthenticatedAppHelpRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRouteWithChildren,
  AuthenticatedAppTemplatesRoute: AuthenticatedAppTemplatesRoute,
  AuthenticatedAppUploadsRoute: AuthenticatedAppUploadsRoute,
  AuthenticatedAppUsageRoute: AuthenticatedAppUsageRoute,
  AuthenticatedAppYoutubeClipperRoute:
    AuthenticatedAppYoutubeClipperRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppProjectsProjectIdRoute:
    AuthenticatedAppProjectsProjectIdRouteWithChildren,
  AuthenticatedAppProjectsNewRoute: AuthenticatedAppProjectsNewRoute,
  AuthenticatedAppProjectsIndexRoute: AuthenticatedAppProjectsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DocsRouteChildren {
  DocsAiEditorRoute: typeof DocsAiEditorRoute
  DocsExportingRoute: typeof DocsExportingRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsTimelineRoute: typeof DocsTimelineRoute
  DocsUploadingMediaRoute: typeof DocsUploadingMediaRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAiEditorRoute: DocsAiEditorRoute,
  DocsExportingRoute: DocsExportingRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsTimelineRoute: DocsTimelineRoute,
  DocsUploadingMediaRoute: DocsUploadingMediaRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface UseCasesRouteChildren {
  UseCasesCoursesRoute: typeof UseCasesCoursesRoute
  UseCasesPodcastsRoute: typeof UseCasesPodcastsRoute
  UseCasesProductDemosRoute: typeof UseCasesProductDemosRoute
  UseCasesShortFormRoute: typeof UseCasesShortFormRoute
  UseCasesYoutubeRoute: typeof UseCasesYoutubeRoute
  UseCasesIndexRoute: typeof UseCasesIndexRoute
}

const UseCasesRouteChildren: UseCasesRouteChildren = {
  UseCasesCoursesRoute: UseCasesCoursesRoute,
  UseCasesPodcastsRoute: UseCasesPodcastsRoute,
  UseCasesProductDemosRoute: UseCasesProductDemosRoute,
  UseCasesShortFormRoute: UseCasesShortFormRoute,
  UseCasesYoutubeRoute: UseCasesYoutubeRoute,
  UseCasesIndexRoute: UseCasesIndexRoute,
}

const UseCasesRouteWithChildren = UseCasesRoute._addFileChildren(
  UseCasesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptableUseRoute: AcceptableUseRoute,
  AiTransparencyRoute: AiTransparencyRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CopyrightRoute: CopyrightRoute,
  DesignSystemRoute: DesignSystemRoute,
  DocsRoute: DocsRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  ImprintRoute: ImprintRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoadmapRoute: RoadmapRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  UseCasesRoute: UseCasesRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
  YoutubeClipperRoute: YoutubeClipperRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthYoutubeCallbackRoute: AuthYoutubeCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
